name: Sample

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        env:
            # secretsに登録した環境変数
            CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
            CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
            CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}

        run: confluence_api_test.py