name: Sample

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CONFLUENCE_URL: https://kojiro30.atlassian.net
  CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
  CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}


jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses : actions/setup-python@main
        with:
          python-version : '3.10.5'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip3 install -r requirements.txt
          ls
      - name: Run Python
        env:
          # secretsに登録した環境変数
          CONFLUENCE_URL: ${{ env.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ env.CONFLUENCE_USERNAME }}
          CONFLUENCE_TOKEN: ${{ env.CONFLUENCE_TOKEN }}
        run: python confluence_api_test.py