name: Sample

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses : actions/setup-python@main
        with:
          python-version : '3.10.5'
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run Python
        env:
            # secretsに登録した環境変数
            CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
            CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
            CONFLUENCE_TOKEN: ${{ secrets.CONFLUENCE_TOKEN }}

        run: confluence_api_test.py